version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    reviewers:
      - "spiegel@uscreen.de"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "@antfu/eslint-config"
          - "eslint*"
          - "c8"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "ulid"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"